In [1]:
import pandas as pd

In [ ]:
#like a python dictionary
data = pd.Series([0.25,0.5,0.75,1.0], index = ['a','b','c','d'])
data

a    0.25
b    0.50
c    0.75
d    1.00
e    1.25
dtype: float64

In [8]:
data['e'] = 1.25
print(data)
print(data['a' : 'c'])

a    0.25
b    0.50
c    0.75
d    1.00
e    1.25
dtype: float64
a    0.25
b    0.50
c    0.75
dtype: float64


Indexers: loc, iloc, and ix

In [9]:
data = pd.Series(['a', 'b', 'c'], index=[1, 3, 5])
data

1    a
3    b
5    c
dtype: object

In [ ]:
print(data[3])
print(data[1:3]) #1:3 uses python indexing

b
3    b
5    c
dtype: object


In [ ]:
print(data.loc[1:3]) #refernces the expilictly named index
print(data.iloc[1:3]) #refernces the python index

1    a
3    b
dtype: object
3    b
5    c
dtype: object


Dataframe

In [ ]:
#Dataframe = chart
area = pd.Series({'California': 423967, 'Texas': 695662,
                  'New York': 141297, 'Florida': 170312,
                  'Illinois': 149995})
pop = pd.Series({'California': 38332521, 'Texas': 26448193,
                 'New York': 19651127, 'Florida': 19552860,
                 'Illinois': 12882135})
data = pd.DataFrame({'area':area, 'pop':pop})
data

,area,pop
California,423967,38332521
Texas,695662,26448193
New York,141297,19651127
Florida,170312,19552860
Illinois,149995,12882135


In [ ]:
data['area']
data.area #same thing but doesnt always work

California    423967
Texas         695662
New York      141297
Florida       170312
Illinois      149995
Name: area, dtype: int64

In [23]:
#We can add stuff too
data['density'] = data['pop'] / data['area']
data

,area,pop,density
California,423967,38332521,90.413926
Texas,695662,26448193,38.018740
New York,141297,19651127,139.076746
Florida,170312,19552860,114.806121
Illinois,149995,12882135,85.883763


In [ ]:
#Dataframe can be a 2d array
print(data.values)
print(data.values[0]) #can access rows

[[4.23967000e+05 3.83325210e+07 9.04139261e+01]
 [6.95662000e+05 2.64481930e+07 3.80187404e+01]
 [1.41297000e+05 1.96511270e+07 1.39076746e+02]
 [1.70312000e+05 1.95528600e+07 1.14806121e+02]
 [1.49995000e+05 1.28821350e+07 8.58837628e+01]]
[4.23967000e+05 3.83325210e+07 9.04139261e+01]


In [29]:
data[data.density > 100]

,area,pop,density
New York,141297,19651127,139.076746
Florida,170312,19552860,114.806121


Index Allignment

In [2]:
import numpy as np
import pandas as pd

In [4]:
area = pd.Series({'Alaska': 1723337, 'Texas': 695662,
                  'California': 423967}, name='area')
population = pd.Series({'California': 38332521, 'Texas': 26448193,
                        'New York': 19651127}, name='population')

In [ ]:
#seperate graphs can be combined
density = population / area
density #chart represents the union of the values

Alaska              NaN
California    90.413926
New York            NaN
Texas         38.018740
dtype: float64

In [8]:
#another example
A = pd.Series([2,4,6], index=[0,1,2])
B = pd.Series([1,3,5], index=[1,2,3])
A+B

0    NaN
1    5.0
2    9.0
3    NaN
dtype: float64

In [10]:
#If you don't want NaN values
A.add(B, fill_value=0)

0    2.0
1    5.0
2    9.0
3    5.0
dtype: float64