In [2]:
import numpy as np

Arrays

In [ ]:
x= np.zeros((3,3), dtype=int) #3x3 array of 0s
y = np.arange(1,10,1)  #range from 1 to 10 in increments of 2
z = np.linspace(1,20,10) #array of 10 evenly spaced values from 1-20
print(x)
print(y)
print(z)

[[0 0 0]
 [0 0 0]
 [0 0 0]]
[1 2 3 4 5 6 7 8 9]
[ 1.          3.11111111  5.22222222  7.33333333  9.44444444 11.55555556
 13.66666667 15.77777778 17.88888889 20.        ]


In [ ]:
x=np.random.random(5) #random numbers between 0-1
y= np.random.normal(0,1,(3,3)) #normally distributed random numbers mean 0 standard deviation 1
z= np.random.randint(0,10,(3,3)) #random int from 0-10
i = np.eye(3, dtype=int) #3x3 identity matrix
print(x)
print(y)
print(z)
print(i) 

[0.78634131 0.55618452 0.1496339  0.62802192 0.62012765]
[[-0.12808462  0.83311855  0.03231074]
 [-0.86622446 -0.63072693 -2.78629704]
 [-0.23191495  0.89671723  0.33012669]]
[[3 5 3]
 [9 2 4]
 [5 2 3]]
[[1 0 0]
 [0 1 0]
 [0 0 1]]


Subarrays(slicing)

In [ ]:
x1 = np.random.randint(10, size=(10))  #One-dimensional array
x2 = np.random.randint(10, size=(3,4)) #Two-dimensional array
x3 = np.random.randint(10, size=(3, 4, 5)) #Three=dimensional array

In [ ]:
print(x1)
print(x1[0])
print(x1[:5]) #Values before 5th value
print(x1[5:]) #values after 5th value
print(x1[::-1]) #reverse

[0 3 6 9 3 8 9 2 5 2]
0
[0 3 6 9 3]
[8 9 2 5 2]
[2 5 2 9 8 3 9 6 3 0]


In [ ]:
print(x2)
print(x2[:2,:2]) #2x2 sub array
x2_sub = x2[:2, :2]
x2_sub[0,0] = 99
print(x2_sub)
print(x2) #altering subarrays alters original array

[[99  5  2  7]
 [ 3  8  1  7]
 [ 1  9  3  9]]
[[99  5]
 [ 3  8]]
[[99  5]
 [ 3  8]]
[[99  5  2  7]
 [ 3  8  1  7]
 [ 1  9  3  9]]


In [ ]:
x2_sub_copy = x2[:2, :2].copy() #creates copy of sub array
print(x2_sub_copy)
x2_sub_copy[0, 0] = 42
print(x2_sub_copy) #altered sub copy
print(x2) #original copy is not altered

[[99  5]
 [ 3  8]]
[[42  5]
 [ 3  8]]
[[99  5  2  7]
 [ 3  8  1  7]
 [ 1  9  3  9]]


Reshaping and concating arrays

In [ ]:
x= np.array([1,2,3])
x.reshape((3,1)) #column vector
x.reshape((1,3)) #row vector
np.concatenate([x,x]) # combines arrays
#np.vstack (vertical stack) np.hstack(horizontal stack)

array([1, 2, 3, 1, 2, 3])

In [ ]:
xstack = np.concatenate([x,x,x])
x1,x2,x3 = np.split(xstack, [3,5])
print(xstack)
print(x1,x2,x3) #split at 3 and 5 value

[1 2 3 1 2 3 1 2 3]
[1 2 3] [1 2] [3 1 2 3]
